version: '3'

services:
  scala_app_db:
    build: ./postgres
    container_name: scala_app_db
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    stdin_open: true
